import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import { TooltipProvider } from "@/components/ui/tooltip";
import { siteOrigin } from "@/features/public-content/seo/routes";
import "./globals.css";

// Nonce-based CSP requires request-time rendering so Next can apply the nonce
// generated by Clerk middleware to every framework and Clerk script.
export const dynamic = "force-dynamic";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  metadataBase: new URL(siteOrigin),
  title: "Importing PH - A simpler way to find the right shipment quote.",
  description: "A simpler way to find the right shipment quote.",
  alternates: {
    canonical: "/",
  },
  openGraph: {
    title: "Importing PH - A simpler way to find the right shipment quote.",
    description: "A simpler way to find the right shipment quote.",
    type: "website",
    url: siteOrigin,
    images: ["/assets/importingph-logo-bg-blue.png"],
  },
  twitter: {
    card: "summary_large_image",
    title: "Importing PH - A simpler way to find the right shipment quote.",
    description: "A simpler way to find the right shipment quote.",
    images: ["/assets/importingph-logo-bg-blue.png"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider dynamic>
      <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >
        <body className="min-h-full bg-background text-foreground">
          <TooltipProvider>{children}</TooltipProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
